version: "3.8" # Not realy needed

services:
  redis:
    image: redis:latest
    container_name: devops_redis
    volumes:
      - redis_data:/data # I asked to add the mapped volume for Redis data persistence in the repository (should be a file mapped to the container)
    ports:
      - "6379:6379"

  web:
    build:
      context: ./web-service
    container_name: devops_web
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - redis

volumes:
  redis_data:
